### ISSUE TITLE
Making nested route?

### ISSUE THREAD

**Issue by SPineapple** [umair-khanzada/role-based-access-control#7]
Is there a possible way to make it a nested route?

for example,
 **Manager** can access into `'/service/service1'`  but can't access into `'/service/service2'` although
**SupportManager** can access into it.

and '/service' is the main route for them.

How can I achieve this?

Please note that I did tried,  by using this example https://reacttraining.com/react-router/web/example/route-config
implementing it in _PrivateRoutes.js_ 
but nested routes are not rendering, help?

**Comment by umair-khanzada** [comment]
@SPineapple Currently it is not supported, I am planning to add nested route support but it may take some time.

**Comment by SPineapple** [comment]
Great! also if possible the nested route would be conditional too, based on the role.
And one last question, what do you mean by module group? and what the usage of it?

Thanks in advance!

**Comment by umair-khanzada** [comment]
Sure, the module group is basically for grouping the navigation as per module ie: (Services module have some links S-1, S-2, ... S-n so rather add all of the links in navbar it'll group it by module and show/expand when you click or hover on that module link)

In simple words for grouping and show as dropdown or accordion.

**Comment by SPineapple** [comment]
Cool, thanks!
I might be asking too much, but can I request that you would also include it in your demo 'grouping by module', this topic is very advance to me, I appreciate your help, a lot  😊

**Comment by umair-khanzada** [comment]
Sure, I'll update this soon.

**Comment by umair-khanzada** [comment]
@SPineapple I have created a version 2 of this demo, version 1 was tightly coupled with the app in which I introduce this technic version 2 is more generic and I have added child route support version 2, now you can create child routes as well as you can add a permission that.

You can find version 2 changes in **[rbac-v2](https://github.com/umair-khanzada/role-based-access-control/tree/rbac-v2)** branch, version 2 is still in under development that's why I didn't merge yet.

Thanks for your patience :)

**Comment by ukhanzada-nisum-com** [comment]
Merged **rbac-v2** in master.

**Comment by umair-khanzada** [comment]
merged rbac-v2 into master.

**Comment by SPineapple** [comment]
sorry for my late response, but thanks a lot !
